services:
  - type: web
    name: email-spam-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_CREDENTIALS
        value: ./credentials.json
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.11
